(function(g){var window=this;var Fwa=function(a,b){var c=[];g.Dl(b,function(a){try{var b=g.qD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.pD(b)&&c.push(a):c.push(a)},a);
return c},Gwa=function(a,b){var c=Fwa(a,b);
(0,g.H)(c,function(a){g.qD.prototype.remove.call(this,a)},a)},w8=function(a,b){g.m1.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.T=a;this.F={};this.P(a,"onMdxReceiversChange",this.I);this.P(a,"presentingplayerstatechange",this.I);this.I()},Hwa=function(){var a=g.RG;
Gwa(a,a.g.Yd(!0))},x8=function(a){g.tH.call(this,"ScreenServiceProxy");
this.dd=a;this.o=[];this.o.push(this.dd.$_s("screenChange",(0,g.z)(this.VT,this)));this.o.push(this.dd.$_s("onlineScreenChange",(0,g.z)(this.gQ,this)))},y8=function(a){g.gH("cloudview",a)},Iwa=function(a){y8("setApiReady_ "+a);
g.sa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},z8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Jwa=function(a){g.jG[a]&&(a=g.jG[a],(0,g.H)(a,function(a){g.hG[a]&&delete g.hG[a]}),a.length=0)},Kwa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},A8=function(){return g.x("yt.mdx.remote.connection_")},B8=function(a){g.sa("yt.mdx.remote.connectData_",a,void 0)},Lwa=function(a){g.sa("yt.mdx.remote.currentScreenId_",a,void 0)},C8=function(){return g.x("yt.mdx.remote.currentScreenId_")},
E8=function(){if(!D8){var a=g.x("yt.mdx.remote.screenService_");
D8=a?new x8(a):null}return D8},F8=function(a){g.sa("yt.mdx.remote.cloudview.initializing_",a,void 0)},G8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},H8=function(a){y8("setCastInstalled_ "+a);
g.TG("yt-remote-cast-installed",a)},I8=function(a){g.gH("cloudview",a)},Mwa=function(a,b){z8().init(a,b)},J8=function(){return!!g.UG("yt-remote-cast-installed")},Nwa=function(){y8("dispose");
var a=z8();a&&a.dispose();g.sa("yt.mdx.remote.cloudview.instance_",null,void 0);Iwa(!1);g.lG(K8);K8.length=0},Owa=function(){var a=window.document.createElement("a");
g.Ld(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ta(a)},Pwa=function(a,b){var c=g.pe("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Md(c,g.hh("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Qwa=function(a){var b=g.gG();
if(b)if(b.clear(a),a)Jwa(a);else for(var c in g.jG)Jwa(c)},L8=function(){var a=Kwa();
a&&a(!1,"No cast extension found")},M8=function(a){return 0<=window.navigator.userAgent.indexOf(a)},N8=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},Rwa=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},O8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},Q8=function(a){var b=A8();
B8(null);a||Lwa("");g.sa("yt.mdx.remote.connection_",a,void 0);P8&&((0,g.H)(P8,function(b){b(a)}),P8.length=0);
b&&!a?g.oG("yt-remote-connection-change",!1):!b&&a&&g.oG("yt-remote-connection-change",!0)},Swa=function(){return g.x("yt.mdx.remote.connectData_")},R8=function(){var a=C8();
if(!a)return null;var b=E8().ge();return g.sH(b,a)},Twa=function(a,b){H8(!0);
F8(!1);Mwa(a,function(a){a?(Iwa(!0),g.mG("yt-remote-cast2-api-ready")):(I8("Failed to initialize cast API."),H8(!1),g.VG("yt-remote-cast-available"),g.VG("yt-remote-cast-receiver"),Nwa());b(a)})},Uwa=function(){return J8()?z8()?z8().getCastSession():(I8("getCastSelector: Cast is not initialized."),null):(I8("getCastSelector: Cast API is not installed!"),null)},Vwa=function(){var a=Owa(),b=window.document.getElementById(a),c=b&&g.wF(b,"loaded");
c||b&&!c||(b=Pwa(a,function(){g.wF(b,"loaded")||(g.xF(b,"loaded","true"),g.mG(a),g.AE(g.Ba(Qwa,a),0))}))},Wwa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},Xwa=function(){if(g.Bpa){var a=2,b=Kwa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;N8("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",L8,c)}},S8=function(a){if(a>=g.Dpa.length)L8();
else{var b=g.Dpa[a],c="chrome-extension://"+b+g.Apa;0<=g.H2.indexOf(b)?Rwa(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,N8(c,L8)):S8(a+1)}):N8(c,function(){S8(a+1)})}},U8=function(a,b){C8();
R8()&&R8();Lwa(a.id);var c=new g.yI(T8,a,O8());c.connect(b,Swa());c.subscribe("beforeDisconnect",function(a){g.oG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){A8()&&(A8(),Q8(null))});
Q8(c)},V8=function(){var a=g.AH();
if(!a)return null;var b=E8().ge();return g.sH(b,a)},W8=function(a){g.gH("remote",a)},X8=function(){var a=A8();
return!!a&&3!=a.getProxyState()},Y8=function(){G8()?z8().stopSession():I8("stopSession called before API ready.");
var a=A8();a&&(a.disconnect(1),Q8(null))},Ywa=function(){var a=E8().dd.$_gos();
var b=R8();b&&A8()&&(g.rH(a,b)||a.push(b));return Wwa(a)},$8=function(a,b){g.YF.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.EB;this.A=this.o=null;this.I=(0,g.z)(this.oO,this);this.F=(0,g.z)(this.pl,this);this.G=(0,g.z)(this.nO,this);this.J=(0,g.z)(this.BO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Gu,this),Zwa(this))):c=3;0!=c&&(b?this.Gu(c):g.AE((0,g.z)(function(){this.Gu(c)},this),0));
var d=Uwa();d&&Z8(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},a9=function(a){return new g.nI(a.B.getPlayerContextData())},$wa=function(a,b,c,d,e){var f=a9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.rI(f,b,d);g.t(c)&&(g.pI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);b9(a,"setPlaylist",l);e||c9(a,f)},Zwa=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Ba(this.xQ,a),this))},a)},axa=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},d9=function(a,b){50>a.C.Kc()&&g.GB(a.C,b)},e9=function(a,b,c){var d=a9(a);
g.pI(d,c);-1E3!=d.g&&(d.g=b);c9(a,d)},b9=function(a,b,c){a.B.sendMessage(b,c)},c9=function(a,b){axa(a);
a.B.setPlayerContextData(g.sI(b));Zwa(a)},Z8=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.pl(null));
a.A=b;a.A&&(f9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.pl(a.A.media[0]))},bxa=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=a9(a);b.contentId!=d.videoId&&f9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.pI(d,a.o.getEstimatedTime());c9(a,d)}else f9("No cast media video. Ignoring state update.")},f9=function(a){g.gH("CP",a)},g9=function(a,b,c){return(0,g.z)(function(a){this.hc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.hc("Retrying "+b+" using MDx browser channel."),b9(this,b,c))},a)},cxa=function(a,b){var c=!1;
z8()||(c=new g.hI(a,b),c.subscribe("yt-remote-cast2-availability-change",function(a){g.TG("yt-remote-cast-available",a);g.oG("yt-remote-cast2-availability-change",a)}),c.subscribe("yt-remote-cast2-receiver-selected",function(a){y8("onReceiverSelected: "+a.friendlyName);
g.TG("yt-remote-cast-receiver",a);g.oG("yt-remote-cast2-receiver-selected",a)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(a){y8("onReceiverResumed: "+a.friendlyName);
g.TG("yt-remote-cast-receiver",a)}),c.subscribe("yt-remote-cast2-session-change",function(a){y8("onSessionChange: "+g.oH(a));
a||g.VG("yt-remote-cast-receiver");g.oG("yt-remote-cast2-session-change",a)}),g.sa("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
y8("cloudview.createSingleton_: "+c);return c},dxa=function(){var a=0<=g.Ib.search(/\ (CrMo|Chrome|CriOS)\//);
return g.UE||a},h9=function(a,b){G8()?z8().setConnectedScreenStatus(a,b):I8("setConnectedScreenStatus called before ready.")},exa=function(){y8("clearCurrentReceiver");
g.VG("yt-remote-cast-receiver")},fxa=function(){if(M8("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Xwa();a({command:"cast.sender.init"});return}}if(!window.chrome||M8("Edge"))L8();else if(Xwa(),M8("Android")&&M8("Chrome/")&&window.navigator.presentation){var a="",b=g.Jh();55<=b?a="55":50<=b&&(a="50");N8("//www.gstatic.com/eureka/clank"+a+g.Apa,L8)}else S8(0)},gxa=function(a){a?(g.TG("yt-remote-session-app",a.app),g.TG("yt-remote-session-name",a.name)):(g.VG("yt-remote-session-app"),g.VG("yt-remote-session-name"));
g.sa("yt.mdx.remote.channelParams_",a,void 0)},hxa=function(){var a=O8();
if(g.Vb(a)){var a=g.zH(),b=g.UG("yt-remote-session-name")||"",c=g.UG("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.sa("yt.mdx.remote.channelParams_",a,void 0)}},ixa=function(){var a=V8();
a?(W8("Resume connection to: "+g.oH(a)),U8(a,0)):(g.HH(),exa(),W8("Skipping connecting because no session screen found."))},jxa=function(a){W8("remote.onCastSessionChange_: "+g.oH(a));
if(a){var b=R8();b&&b.id==a.id?h9(b.id,"YouTube TV"):(b&&Y8(),U8(a,1))}else A8()&&Y8()},kxa=function(){var a=Ywa(),b=R8();
b||(b=V8());return g.ab(a,function(a){return b&&g.lH(b,a.key)?!0:!1})},lxa=function(){var a=g.UG("yt-remote-cast-receiver");
return a?a.friendlyName:null},mxa=function(a,b,c,d,e){dxa()?cxa(b,e)&&(F8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Twa(a,c):(window.__onGCastApiAvailable=function(b,d){b?Twa(a,c):(I8("Failed to load cast API: "+d),H8(!1),F8(!1),g.VG("yt-remote-cast-available"),g.VG("yt-remote-cast-receiver"),Nwa(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Vwa():fxa())):y8("Cannot initialize because not running Chrome")},
nxa=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Cg(a)||"";b&&(this.port=":"+b);this.domain=g.Bg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Sa(a,"10.0")&&(this.o=!1))},i9=function(){var a=kxa();
!a&&J8()&&lxa()&&(a={key:"cast-selector-receiver",name:lxa()});return a},oxa=function(){var a=Ywa();
J8()&&g.UG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},pxa=function(a){var b={device:"Desktop",
app:"youtube-desktop"},b=g.RD("MDX_CONFIG")||b;g.RG&&Hwa();g.BH();T8||(T8=new nxa(b?b.loungeApiHost:void 0),g.JH()&&(T8.g="/api/loungedev"));P8||(P8=g.x("yt.mdx.remote.deferredProxies_")||[],g.sa("yt.mdx.remote.deferredProxies_",P8,void 0));hxa();var c=E8();if(!c){var d=new g.UH(T8);g.sa("yt.mdx.remote.screenService_",d,void 0);c=E8();mxa(a,d,function(a){a?C8()&&h9(C8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.oG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript),
b?b.appId:void 0)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.sa("yt.mdx.remote.initialized_",!0,void 0),W8("Initializing: "+g.tg(b)),j9.push(g.kG("yt-remote-cast2-availability-change",function(){g.oG("yt-remote-receiver-availability-change")})),j9.push(g.kG("yt-remote-cast2-receiver-selected",function(){B8(null);
g.oG("yt-remote-auto-connect","cast-selector-receiver")})),j9.push(g.kG("yt-remote-cast2-receiver-resumed",function(){g.oG("yt-remote-receiver-resumed","cast-selector-receiver")})),j9.push(g.kG("yt-remote-cast2-session-change",jxa)),j9.push(g.kG("yt-remote-connection-change",function(a){a?h9(C8(),"YouTube TV"):V8()||(h9(null,null),exa())})),a=O8(),b.isAuto&&(a.id+="#dial"),g.cF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),W8(" -- with channel params: "+
g.tg(a)),gxa(a),c.start(),C8()||ixa())},k9=function(){J8()?z8()?G8()?(y8("Requesting cast selector."),z8().requestSession()):(y8("Wait for cast API to be ready to request the session."),K8.push(g.kG("yt-remote-cast2-api-ready",k9))):I8("requestCastSelector: Cast is not initialized."):I8("requestCastSelector: Cast API is not installed!")},l9=function(a,b,c){g.L.call(this);
this.F=a;this.T=b;this.o=new g.VF(this);g.M(this,this.o);this.o.P(b,"onCaptionsTrackListChanged",this.AP);this.o.P(b,"captionschanged",this.mO);this.o.P(b,"captionssettingschanged",this.NC);this.o.P(b,"videoplayerreset",this.so);this.o.P(b,"mdxautoplaycancel",this.aH);this.N=this.o.P(b,"onVolumeChange",this.hB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.sB,this);c.subscribe("remotePlayerChange",this.sl,this);c.subscribe("remoteQueueChange",this.so,this);c.subscribe("autoplayUpNext",this.UA,
this);c.subscribe("previousNextChange",this.pB,this);c.subscribe("nowAutoplaying",this.iB,this);c.subscribe("autoplayDismissed",this.TA,this);this.suggestion=null;this.G=new g.kQ(64);this.A=new g.rt(this.IC,500,this);g.M(this,this.A);this.B=new g.rt(this.JC,1E3,this);g.M(this,this.B);this.C={};this.J=new g.rt(this.aD,1E3,this);g.M(this,this.J);this.I=new g.mk(this.kM,1E3,this);g.M(this,this.I);this.L=g.y;this.NC();this.so();this.sl()},m9=function(a,b){var c=a.F,d=a.T.ga().lengthSeconds;
c.I=b||0;c.g.X("progresssync",b,d)},qxa=function(a){m9(a,0);
a.A.stop();n9(a,new g.kQ(64))},p9=function(a,b){if(o9(a)&&!a.D){var c=null;
b&&(c={style:a.T.si()},g.ac(c,b));a.g.BC(a.T.ga().videoId,c);a.C=a9(a.g).o}},q9=function(a,b){var c=a.T.Uf();
c?$wa(a.g,a.T.ga().videoId,b,c.de(),c.listId.toString()):$wa(a.g,a.T.ga().videoId,b);n9(a,new g.kQ(1))},rxa=function(a,b){if(b){var c=a.T.xc("captions","tracklist",{Ky:1});
c&&c.length?(a.T.Cd("captions","track",b),a.D=!1):(a.T.Xk("captions"),a.D=!0)}else a.T.Cd("captions","track",{})},o9=function(a){return a9(a.g).videoId==a.T.ga().videoId},n9=function(a,b){a.B.stop();
var c=a.G;if(!g.qQ(c,b)){var d=g.W(b,2);if(d!=g.W(a.G,2)){var e=a.T;g.e2(e.app,d,e.playerType)}a.G=b;sxa(a.F,c,b)}},r9=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.WD()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.mW(this,250);g.M(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);txa(this,g.kV(a))},txa=function(a,b){if(3==a.A.Ya()){var c={RECEIVER_NAME:a.A.xc("remote","currentReceiver").name},c=g.W(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.xb()||g.W(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",
c);
a.Ga("statustext",c);a.o.show()}else a.o.hide()},s9=function(a){g.gW.call(this,a);
this.A={key:g.qH(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.kQ(64);this.I=0;var b=g.dV(a).F;b&&(b=b.A&&b.A.g)&&(b=new w8(a,b),g.M(this,b));b=new r9(a);g.M(this,b);g.FV(a,b.element,4)},sxa=function(a,b,c){a.F=c;
a.g.X("presentingplayerstatechange",new g.vQ(c,b))},t9=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)Y8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ga().videoId;if(c||d){var e=a.g.Uf();if(e){var f=[];for(var k=0;k<e.getLength();k++)f[k]=e.dc(k).videoId}else f=[a.g.ga().videoId];c={videoIds:f,listId:c,videoId:d,index:Math.max(a.g.xz(),0),currentTime:a.g.getCurrentTime()}}else c=null;W8("Connecting to: "+g.tg(b));"cast-selector-receiver"==b.key?(B8(c||null),c=c||null,G8()?z8().setLaunchParams(c):I8("setLaunchParams called before ready.")):!c&&X8()&&C8()==b.key?g.oG("yt-remote-connection-change",!0):
(Y8(),B8(c||null),c=E8().ge(),(c=g.sH(c,b.key))&&U8(c,1))}};
g.p(w8,g.m1);w8.prototype.I=function(){var a=this.T.xc("remote","receivers");a&&1<a.length&&!this.T.xc("remote","quickCast")?(this.F=g.Eb(a,this.B,this),g.n1(this,(0,g.I)(a,this.B)),a=this.T.xc("remote","currentReceiver"),this.qf(this.B(a)),this.enable(!0)):this.enable(!1)};
w8.prototype.B=function(a){return a.key};
w8.prototype.pf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
w8.prototype.qd=function(a){g.m1.prototype.qd.call(this,a);this.T.Cd("remote","currentReceiver",this.F[a]);this.A.Ub()};
g.D(x8,g.tH);g.h=x8.prototype;g.h.ge=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.pp=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.Xo=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.o.length;a<b;++a)this.dd.$_ubk(this.o[a]);this.o.length=0;this.dd=null;x8.Z.W.call(this)};
g.h.VT=function(){this.X("screenChange")};
g.h.gQ=function(){this.X("onlineScreenChange")};
var D8=null,K8=[],P8=null,T8=null;g.D($8,g.YF);g.h=$8.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,g9(this,"play")):b9(this,"play"),e9(this,1,g.qI(a9(this))),this.X("remotePlayerChange")):d9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,g9(this,"pause")):b9(this,"pause"),e9(this,2,g.qI(a9(this))),this.X("remotePlayerChange")):d9(this,this.pause)};
g.h.nD=function(a){if(1==this.g){if(this.o){var b=a9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.xb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,g9(this,"seekTo",{newTime:a}))}else b9(this,"seekTo",{newTime:a});e9(this,3,a);this.X("remotePlayerChange")}else d9(this,g.Ba(this.nD,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,g9(this,"stopVideo")):b9(this,"stopVideo");var a=a9(this);a.index=-1;a.videoId="";g.oI(a);c9(this,a);this.X("remotePlayerChange")}else d9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=a9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){f9("set receiver volume: "+d)},this),(0,g.z)(function(){this.hc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){f9("set receiver muted: "+b)},this),(0,g.z)(function(){this.hc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);b9(this,"setVolume",e)}c.muted=b;c.volume=a;c9(this,c)}else d9(this,g.Ba(this.setVolume,a,b))};
g.h.BC=function(a,b){if(1==this.g){var c=a9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.tg(b.style),g.ac(d,c.o));b9(this,"setSubtitlesTrack",d);c9(this,c)}else d9(this,g.Ba(this.BC,a,b))};
g.h.Fu=function(a,b){if(1==this.g){b9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Tc.id});var c=a9(this);c.audioTrackId=b.Tc.id;c9(this,c)}else d9(this,g.Ba(this.Fu,a,b))};
g.h.mD=function(a,b){if(1==this.g){if(a&&b){var c=a9(this);g.rI(c,a,b);c9(this,c)}b9(this,"previous")}else d9(this,g.Ba(this.mD,a,b))};
g.h.lD=function(a,b){if(1==this.g){if(a&&b){var c=a9(this);g.rI(c,a,b);c9(this,c)}b9(this,"next")}else d9(this,g.Ba(this.lD,a,b))};
g.h.ax=function(){1==this.g?b9(this,"dismissAutoplay"):d9(this,this.ax)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.X("proxyStateChange",a,this.g)}$8.Z.dispose.call(this)};
g.h.W=function(){axa(this);this.B=null;this.C.clear();Z8(this,null);$8.Z.W.call(this)};
g.h.Gu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.X("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.HB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.xQ=function(a,b){this.X(a,b)};
g.h.oO=function(a){if(!a)this.pl(null),Z8(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=a9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)f9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,c9(this,b)}};
g.h.pl=function(a){f9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),bxa(this),this.X("remotePlayerChange")};
g.h.nO=function(a){a?(bxa(this),this.X("remotePlayerChange")):this.pl(null)};
g.h.BO=function(){var a=Uwa();a&&Z8(this,a)};
g.h.hc=function(a){g.gH("CP",a)};
var j9=[];g.h=nxa.prototype;g.h.di=function(a){var b=this.g;if(g.t(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Jg(b+a,{})};
g.h.Eu=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Vb:g.Ba(this.QT,c,!0),onError:g.Ba(this.PT,d),Ed:g.Ba(this.RT,d)};b&&(c.Ob=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.OE(a,c)};
g.h.QT=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.PT=function(a,b){a(Error("Request error: "+b.status))};
g.h.RT=function(a){a(Error("request timed out"))};g.p(l9,g.L);g.h=l9.prototype;g.h.W=function(){g.L.prototype.W.call(this);this.A.stop();this.B.stop();this.L();this.g.unsubscribe("proxyStateChange",this.sB,this);this.g.unsubscribe("remotePlayerChange",this.sl,this);this.g.unsubscribe("remoteQueueChange",this.so,this);this.g.unsubscribe("autoplayUpNext",this.UA,this);this.g.unsubscribe("previousNextChange",this.pB,this);this.g.unsubscribe("nowAutoplaying",this.iB,this);this.g.unsubscribe("autoplayDismissed",this.TA,this);this.g=this.F=null};
g.h.Uz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(o9(this)){if(1081!=a9(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":a9(this.g).xb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.hj(c[0],c[1]);break;case "control_subtitles_set_track":p9(this,c[0]);break;case "control_set_audio_track":c=c[0],o9(this)&&this.g.Fu(this.T.ga().videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":q9(this,this.T.getCurrentTime());break;case "control_seek":q9(this,c[0]);break;case "control_subtitles_set_track":p9(this,c[0]);break;case "control_set_audio_track":c=c[0],o9(this)&&this.g.Fu(this.T.ga().videoId,c)}};
g.h.mO=function(a){this.Uz("control_subtitles_set_track",g.Vb(a)?null:a)};
g.h.NC=function(){var a=this.T.xc("captions","track");g.Vb(a)||p9(this,a)};
g.h.hB=function(a){if(o9(this)){this.g.unsubscribe("remotePlayerChange",this.sl,this);var b=Math.round(a.volume);a=!!a.muted;var c=a9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.J.start();this.g.subscribe("remotePlayerChange",this.sl,this)}};
g.h.AP=function(){g.Vb(this.C)||rxa(this,this.C);this.D=!1};
g.h.sB=function(a,b){this.B.stop();2==b&&this.JC()};
g.h.sl=function(){if(o9(this)){this.A.stop();var a=a9(this.g);switch(a.g){case 1081:n9(this,new g.kQ(8));break;case 1:this.IC();n9(this,new g.kQ(8));break;case 1083:case 3:n9(this,new g.kQ(9));break;case 0:n9(this,new g.kQ(2));this.I.stop();m9(this,this.T.ga().lengthSeconds);break;case 1082:n9(this,new g.kQ(4));break;case 2:n9(this,new g.kQ(4));m9(this,g.qI(a));break;case -1:n9(this,new g.kQ(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},n9(this,new g.kQ(128,
a))}var a=a9(this.g).o,b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,rxa(this,a));a=a9(this.g);-1==a.volume||Math.round(this.T.getVolume())==a.volume&&this.T.Le()==a.muted||this.J.isActive()||this.aD()}else qxa(this)};
g.h.pB=function(){this.T.X("mdxpreviousnextchange")};
g.h.so=function(){o9(this)||qxa(this)};
g.h.aH=function(){this.g.ax()};
g.h.UA=function(a){a&&(a=g.OE("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},Vb:(0,g.z)(this.xR,this)}))&&(this.L=(0,g.z)(a.abort,a))};
g.h.xR=function(a,b){var c=new g.iP({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.T.X("mdxautoplayupnext",c)};
g.h.iB=function(a){(0,window.isNaN)(a)||this.T.X("mdxnowautoplaying",a)};
g.h.TA=function(){this.T.X("mdxautoplaycanceled")};
g.h.kM=function(a,b){-1==a9(this.g).g?q9(this,a):b&&this.g.nD(a)};
g.h.aD=function(){if(o9(this)){var a=a9(this.g);this.o.Ca(this.N);a.muted?this.T.mute():this.T.Xf();this.T.setVolume(a.volume);this.N=this.o.P(this.T,"onVolumeChange",this.hB)}};
g.h.IC=function(){this.A.stop();if(!this.g.na()){var a=a9(this.g);a.xb()&&n9(this,new g.kQ(8));m9(this,g.qI(a));this.A.start()}};
g.h.JC=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(r9,g.Y);r9.prototype.B=function(a){txa(this,a.state)};g.p(s9,g.gW);g.h=s9.prototype;g.h.create=function(){pxa(g.vN(g.X(this.g)));this.D.push(g.kG("yt-remote-before-disconnect",this.jO,this));this.D.push(g.kG("yt-remote-connection-change",this.HQ,this));this.D.push(g.kG("yt-remote-receiver-availability-change",this.qB,this));this.D.push(g.kG("yt-remote-auto-connect",this.FQ,this));this.D.push(g.kG("yt-remote-receiver-resumed",this.EQ,this));this.qB()};
g.h.load=function(){this.g.qq();g.gW.prototype.load.call(this);this.C=new l9(this,this.g,this.o);var a=Swa(),a=a?a.currentTime:0,b=X8()?new $8(A8(),void 0):null;0==a&&b&&(a=g.qI(a9(b)));0!=a&&(this.I=a||0,this.g.X("progresssync",a,void 0));sxa(this,this.F,this.F);g.j2(this.g.app,6)};
g.h.unload=function(){this.g.X("mdxautoplaycanceled");this.B=this.A;g.Te(this.C,this.o);this.o=this.C=null;g.gW.prototype.unload.call(this);g.j2(this.g.app,5)};
g.h.W=function(){g.lG(this.D);g.gW.prototype.W.call(this)};
g.h.dl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.Uz.apply(this.C,[].concat([a],g.na(c)))};
g.h.MH=function(){return this.loaded?this.C.suggestion:null};
g.h.Of=function(){return this.o?a9(this.o).Of:!1};
g.h.hasNext=function(){return this.o?a9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.QL=function(){var a=a9(this.o),b=this.g.ga();return{allowSeeking:this.g.Rd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+((0,g.G)()-a.A)/1E3:a.C,isPeggedToLive:1>=(a.F?a.B+((0,g.G)()-a.A)/1E3:a.B)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.F?a.B+((0,g.G)()-a.A)/1E3:a.B,seekableStart:0<a.D?a.D+((0,g.G)()-a.A)/1E3:a.D}};
g.h.RL=function(){this.o&&this.o.lD()};
g.h.SL=function(){this.o&&this.o.mD()};
g.h.jO=function(a){1==a&&(this.J=this.o?a9(this.o):null)};
g.h.HQ=function(){var a=X8()?new $8(A8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Se(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.ga().videoId&&this.g.vz(a.videoId,g.qI(a)));this.g.X("videodatachange","newdata",this.g.ga(),3)};
g.h.qB=function(){this.G=[this.A].concat(oxa());var a=i9()||this.A;t9(this,a);this.g.ya("onMdxReceiversChange")};
g.h.FQ=function(){var a=i9();t9(this,a)};
g.h.EQ=function(){this.B=i9()};
g.h.PL=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?k9():t9(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&k9(),!0):!1}};
g.h.TL=function(){b9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Fd=function(){return!1};g.vZ.remote=s9;})(_yt_player);
